# Generated by Django 4.2.6 on 2025-07-23 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=225, verbose_name='Nama Pasien')),
                ('patientBirthDate', models.DateField(verbose_name='Tanggal Lahir')),
                ('patientGender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1, verbose_name='Jenis Kelamin')),
                ('patientID', models.CharField(default=None, max_length=16, unique=True, verbose_name='No Pasien')),
            ],
            options={
                'verbose_name_plural': 'Data Pasien',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads/')),
                ('annotation', models.FileField(upload_to='uploads/')),
                ('annotated_image', models.FileField(upload_to='static/')),
                ('imageDate', models.DateField(verbose_name='Tanggal Image diambil (mm/dd/yyyy)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patientName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.patientdata')),
            ],
        ),
        migrations.CreateModel(
            name='CroppedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='static/')),
                ('predictionResult', models.TextField(blank=True, null=True)),
                ('predictionDate', models.DateField(verbose_name='Tanggal Image diprediksi (mm/dd/yyyy)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rawImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.uploadedfile')),
            ],
        ),
    ]
