# Generated by Django 4.2.6 on 2025-08-15 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordNum', models.CharField(default='UNKNOWN', max_length=225, verbose_name='Nomor Rekam Medis')),
                ('institutionName', models.CharField(max_length=225, verbose_name='Institusi')),
                ('recordDate', models.DateField(verbose_name='Tanggal pengambilan')),
                ('recordID', models.CharField(default=None, max_length=16, unique=True, verbose_name='Record ID')),
            ],
            options={
                'verbose_name_plural': 'Medical Records',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads/')),
                ('annotation', models.FileField(upload_to='uploads/')),
                ('annotated_image', models.FileField(upload_to='static/')),
                ('imageDate', models.DateField(verbose_name='Tanggal Image diambil (mm/dd/yyyy)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('RecordNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.recorddata')),
            ],
        ),
        migrations.CreateModel(
            name='CroppedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='static/')),
                ('predictionResult', models.TextField(blank=True, null=True)),
                ('predictionDate', models.DateField(verbose_name='Tanggal Image diprediksi (mm/dd/yyyy)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rawImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.uploadedfile')),
            ],
        ),
    ]
