# Generated by Django 4.2.6 on 2025-07-24 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdata',
            options={'verbose_name_plural': 'Patient Data'},
        ),
    ]
