# Generated by Django 4.2.6 on 2025-09-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddata',
            name='project',
            field=models.FileField(upload_to='uploads/', verbose_name='Qupath Project'),
        ),
        migrations.AlterField(
            model_name='recorddata',
            name='recordDate',
            field=models.DateField(verbose_name='Tanggal Pengambilan'),
        ),
    ]
