# Generated by Django 4.2.6 on 2025-09-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_recorddata_project_alter_recorddata_recorddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppedimage',
            name='originalLabel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
